name: onigami
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.18.2 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.4
  image_picker: 0.8.6
  sp_util: 2.0.3
  google_fonts: 3.0.1
  material_design_icons_flutter: 6.0.7096
  location: 4.4.0
  geolocator: 9.0.2
  intl: ^0.18.0
  loading_animation_widget: ^1.2.0+4
  animated_bottom_navigation_bar: ^1.1.0+1
  firebase_core: ^2.7.1
  firebase_auth: ^4.2.2
  introduction_screen: ^3.1.6
  cloud_firestore: ^4.4.4
  cached_network_image: 3.2.3
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  assets: 
    - assets/images/
  uses-material-design: true

