// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB4_aofDoHWW0oMihSXLypJ0N3MKA0GEMI',
    appId: '1:776400766845:web:380b67388c53d7826d2e14',
    messagingSenderId: '776400766845',
    projectId: 'onigami-e5b28',
    authDomain: 'onigami-e5b28.firebaseapp.com',
    storageBucket: 'onigami-e5b28.appspot.com',
    measurementId: 'G-GJ0CGX8BBP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCRweEOQxRD_bQ1SY6-MU9Gp9qZVGyIr6A',
    appId: '1:776400766845:android:26392617c32fc8e76d2e14',
    messagingSenderId: '776400766845',
    projectId: 'onigami-e5b28',
    storageBucket: 'onigami-e5b28.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAtA_q8Hg-Al8eQfbN9HAuuMV94cMGQuAo',
    appId: '1:776400766845:ios:d43aba2b4d10d39c6d2e14',
    messagingSenderId: '776400766845',
    projectId: 'onigami-e5b28',
    storageBucket: 'onigami-e5b28.appspot.com',
    androidClientId: '776400766845-ueoremb4pusbsudr2le4ogequ0hi3s60.apps.googleusercontent.com',
    iosClientId: '776400766845-san71o9jv2nquptu30or2vhqj8bcat8s.apps.googleusercontent.com',
    iosBundleId: 'com.example.getxPatternStarter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAtA_q8Hg-Al8eQfbN9HAuuMV94cMGQuAo',
    appId: '1:776400766845:ios:d43aba2b4d10d39c6d2e14',
    messagingSenderId: '776400766845',
    projectId: 'onigami-e5b28',
    storageBucket: 'onigami-e5b28.appspot.com',
    androidClientId: '776400766845-ueoremb4pusbsudr2le4ogequ0hi3s60.apps.googleusercontent.com',
    iosClientId: '776400766845-san71o9jv2nquptu30or2vhqj8bcat8s.apps.googleusercontent.com',
    iosBundleId: 'com.example.getxPatternStarter',
  );
}
